addSbtPlugin("com.typesafe.sbt"   % "sbt-git"            % "0.9.3")
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.14.0")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"       % "1.4.0")
addSbtPlugin("io.get-coursier"    % "sbt-coursier"       % "1.0.0")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"    % "2.2.1")
